const ADDTOCART = "ADDTOCART";
const QUANTITY = "QUANTITY";
const REMOVEITEM = "REMOVEITEM";
const MODALSTATE = "MODALSTATE";
const UPDATECART = "UPDATECART";
const PAYMENT = "PAYMENT";
export { ADDTOCART, QUANTITY, REMOVEITEM, MODALSTATE, UPDATECART, PAYMENT };
